creation_rules:
  - path_regex: common/.*\.yaml$
    key_groups:
      - age:
          - age1qt9kett9z4uwlr6wz0tqclhm24a8e6czfpkxklj2gcsnf9gaud8qt6a7hs
          - age19ezywulkd2zwpenzhrydemct7jr8xw4z39ss3pe8lnu2lmf2wunqdkzzsg

  - path_regex: zephyrus-g14/.*\.yaml$
    key_groups:
      - age:
          - age1qt9kett9z4uwlr6wz0tqclhm24a8e6czfpkxklj2gcsnf9gaud8qt6a7hs
          - age19ezywulkd2zwpenzhrydemct7jr8xw4z39ss3pe8lnu2lmf2wunqdkzzsg
